### PR TITLE
Handle conflicting modified version

### LINKED ISSUE #72: Concurrency handling
Handle concurrency issues and notify frontend appropriately.

- [x] Research which cases we want to handle
- [x] Research how this can be detected in `tokio-postgres`
- [x] Add utility for detecting concurrency exceptions
- [x] Handle following cases:
  - [x] Document version creation
  - [x] Document version state update
  - [x] Document version content update
- [x] Add `updated_at` to document version schema
- [x] Add `updated_at` to document version return and update models
- [x] Compare `updated_at` to determine problems
- [x] Return a well defined response to frontend

### LINKED ISSUE #82: Handling concurrency: modifying versions
Last modification time should be sent for backend to confirm there were no changes in the meantime (i.e. between the moment when the user loads the version for modification and submits their modifications).

See #72

### PR DESCRIPTION
**Pull request by Dove6**
Closes #82

### CODE REVIEW

File: frontend/src/models/ChangeVersionState.tsx [hunk 1]
```diff
@@ -0,0 +1,8 @@
+import { DocumentVersionState } from "./DocumentVersion";
+
+export type ChangeVersionState = {
+    newState: DocumentVersionState,
+    updatedAt: string,
+}
+
+export default ChangeVersionState;
```
Comment (MortonPL) [inline frontend/src/models/ChangeVersionState.tsx:8]: Files should end with an empty new line.

**Review by MortonPL — APPROVED** [review]
LGTM.
